export enum TokenType {
    KEYWORD,
    SYMBOL,
    IDENTIFIER,
    INT_CONST,
    STRING_CONST,
    NONE
}

export enum Keyword {
    CLASS,
    METHOD,
    FUNCTION,
    CONSTRUCTOR,
    INT,
    BOOLEAN,
    CHAR,
    VOID,
    VAR,
    STATIC,
    FIELD,
    LET,
    DO,
    IF,
    ELSE,
    WHILE,
    RETURN,
    TRUE,
    FALSE,
    NULL,
    THIS
}

export const KeywordMap = new Map<string, Keyword>([
    ["class", Keyword.CLASS],
    ["method", Keyword.METHOD],
    ["function", Keyword.FUNCTION],
    ["constructor", Keyword.CONSTRUCTOR],
    ["int", Keyword.INT],
    ["boolean", Keyword.BOOLEAN],
    ["char", Keyword.CHAR],
    ["void", Keyword.VOID],
    ["var", Keyword.VAR],
    ["static", Keyword.STATIC],
    ["field", Keyword.FIELD],
    ["let", Keyword.LET],
    ["do", Keyword.DO],
    ["if", Keyword.IF],
    ["else", Keyword.ELSE],
    ["while", Keyword.WHILE],
    ["return", Keyword.RETURN],
    ["true", Keyword.TRUE],
    ["false", Keyword.FALSE],
    ["null", Keyword.NULL],
    ["this", Keyword.THIS],
]);

export class Token {
    constructor(public type: TokenType, public value: string) {}
}


export const Patterns: [RegExp, TokenType][] = [
    [/^class/, TokenType.KEYWORD],
    [/^method/, TokenType.KEYWORD],
    [/^function/, TokenType.KEYWORD],
    [/^constructor/, TokenType.KEYWORD],
    [/^int/, TokenType.KEYWORD],
    [/^boolean/, TokenType.KEYWORD],
    [/^char/, TokenType.KEYWORD],
    [/^void/, TokenType.KEYWORD],
    [/^var/, TokenType.KEYWORD],
    [/^static/, TokenType.KEYWORD],
    [/^field/, TokenType.KEYWORD],
    [/^let/, TokenType.KEYWORD],
    [/^do/, TokenType.KEYWORD],
    [/^if/, TokenType.KEYWORD],
    [/^else/, TokenType.KEYWORD],
    [/^while/, TokenType.KEYWORD],
    [/^return/, TokenType.KEYWORD],
    [/^true/, TokenType.KEYWORD],
    [/^false/, TokenType.KEYWORD],
    [/^null/, TokenType.KEYWORD],
    [/^{/, TokenType.SYMBOL],
    [/^}/, TokenType.SYMBOL],
    [/^\(/, TokenType.SYMBOL],
    [/^\)/, TokenType.SYMBOL],
    [/^\[/, TokenType.SYMBOL],
    [/^]/, TokenType.SYMBOL],
    [/^./, TokenType.SYMBOL],
    [/^,/, TokenType.SYMBOL],
    [/^;/, TokenType.SYMBOL],
    [/^\+/, TokenType.SYMBOL],
    [/^-/, TokenType.SYMBOL],
    [/^\*/, TokenType.SYMBOL],
    [/^\//, TokenType.SYMBOL],
    [/^&/, TokenType.SYMBOL],
    [/^|/, TokenType.SYMBOL],
    [/^</, TokenType.SYMBOL],
    [/^>/, TokenType.SYMBOL],
    [/^=/, TokenType.SYMBOL],
    [/^~/, TokenType.SYMBOL],
    [/^[0-32767]/,TokenType.INT_CONST],
    [/^"[^"\\n]"/, TokenType.STRING_CONST],
    [/^[a-zA-Z_]+\w*/, TokenType.IDENTIFIER]
];
